# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'PartyUp' do
    pod 'JSQMessagesViewController'
    pod 'libPusher', '~> 1.6'
end

target 'PartyUpTests' do

end

